build:
  stage: build
  artifacts: 
    paths: 
      - .stack-work/
    expire_in: 5 mins
  script:
    - source /home/gitlab-runner/.ghcup/env
    - stack build
  only:
    refs:
      - master

unit-test:
  stage: test
  script:
    - stack test
  only:
    refs:
      - master

integration-test:
  stage: test
  script:
    - python3 integration_runner.py
  only:
    refs:
      - master