name:                WACC40
version:             0.1.0.0
git:                 "https://gitlab.doc.ic.ac.uk/lab2223_spring/WACC_40"
author:              Hamish Mccreanor <hwm21@ic.ac.uk>, Priyansh Mahajan <pm521@ic.ac.uk>, Seyhan Khan <sk2721@ic.ac.uk>, Kelan Benson <kjb121@ic.ac.uk>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- text
- containers
- megaparsec
- hspec-megaparsec
- parser-combinators
- hspec
- transformers
- mtl
- filepath
- haskeline

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-warn-incomplete-uni-patterns
- -fno-warn-orphans

library:
  source-dirs: 
  - src

executables:
  WACC40-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WACC40

tests:
  WACC40-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - WACC40